services:
  app:
    build:
      target: builder
    command: >
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/build/app
      - ./data/uploads:/build/data/uploads   
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - POSTGRES_HOST=postgres   
  

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  qdrant:
    ports:
      - "6333:6333"
      - "6334:6334"